name: 'Verificação básica de código'

on:
  push:
    branches:
      - 'main'
      - 'feat/*'

jobs:
  basic-check:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Subir o Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Instalar as dependências
        run: npm install

      - name: Rodar o ESLint
        run: npm run lint

      - name: Rodar os testes unitários
        run: npm run test:unit

      - name: Subir o Postgres
        run: npm run docker:up:postgres

      - name: Rodar os testes de integração
        run: npm run test:int

      - name: Parar o Postgres
        run: npm run docker:down:postgres